export const VIEW_PROFILE_REQUEST = 'VIEW_PROFILE_REQUEST'
export const VIEW_PROFILE_SUCCESS = 'VIEW_PROFILE_SUCCESS'
export const VIEW_PROFILE_FAIL = 'VIEW_PROFILE_FAIL'
export const VIEW_PROFILE_RESET = 'VIEW_PROFILE_RESET'

export const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST'
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS'
export const UPDATE_PROFILE_FAIL = 'UPDATE_PROFILE_FAIL'
export const UPDATE_PROFILE_RESET = 'UPDATE_PROFILE_RESET'